# -*- coding: utf-8 -*-
"""Forensics xG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXahst9EouNaxkFii2bNbwgR_lbGrts5
"""

# Install all required libraries
!pip install -q streamlit mplsoccer pandas matplotlib numpy

print("✅ All libraries installed successfully!")

!wget -q -O - ipv4.icanhazip.com

import os
import shutil
if os.path.exists('.streamlit'):
    shutil.rmtree('.streamlit')
    print("Environment Purged.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile forensics_app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# 
# # --- 1. CONFIGURATION ---
# st.set_page_config(page_title="Forensics xG", layout="wide")
# 
# # --- 2. ASSETS ---
# # Using the white fingerprint icon for high contrast
# ICON_URL = "https://img.icons8.com/ios-filled/100/ffffff/fingerprint.png"
# BG_URL = "https://raw.githubusercontent.com/jczpineda/Forensics-xG/main/Background.jpg"
# 
# # --- 3. CSS STYLING ---
# st.markdown(f"""
#     <style>
#     /* Main Background */
#     .stApp {{
#         background: linear-gradient(rgba(10, 25, 47, 0.95), rgba(10, 25, 47, 0.98)), url("{BG_URL}");
#         background-size: cover;
#     }}
#     /* Sidebar Deep Navy Fix */
#     [data-testid="stSidebar"] {{
#         background-color: #020c1b !important;
#         border-right: 1px solid #1e293b;
#     }}
#     /* Standard UI Overrides */
#     h1, h2, h3, h4, p, span, label, div {{
#         color: white !important;
#         font-family: sans-serif !important;
#         font-style: normal !important;
#     }}
#     /* Dropdown box visibility */
#     div[data-baseweb="select"] > div {{
#         background-color: #1e293b !important;
#         border: 1px solid #475569 !important;
#     }}
#     </style>
# """, unsafe_allow_html=True)
# 
# # --- 4. DATA ENGINE ---
# @st.cache_data
# def get_analysis_data(dataset_name):
#     players = ["Bruno Fernandes", "Rashford", "Garnacho", "Mainoo", "Casemiro", "Onana", "Dalot", "Martinez", "Hojlund", "Mount"]
#     np.random.seed(42)
#     if "Goalkeeper" in dataset_name:
#         return pd.DataFrame({
#             "Player": players, "PSxG +/-": np.random.uniform(-5.0, 5.0, 10),
#             "Save %": np.random.uniform(60.0, 85.0, 10), "90s": np.random.uniform(5.0, 30.0, 10)
#         })
#     else:
#         return pd.DataFrame({
#             "Player": players, "xA": np.random.uniform(0.0, 10.0, 10),
#             "Key Passes": np.random.randint(0, 80, 10), "90s": np.random.uniform(5.0, 30.0, 10)
#         })
# 
# # --- 5. SIDEBAR (Updated Branding & Labels) ---
# with st.sidebar:
#     # Stable Header Layout
#     st.markdown(f"""
#     <div style="display: flex; align-items: center; margin-bottom: 20px;">
#         <img src="{ICON_URL}" style="width: 45px; margin-right: 15px;">
#         <div style="color: white; font-size: 18px; font-weight: 800; line-height: 1.1;">
#             FORENSICS<br>ANALYSIS
#         </div>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     st.divider()
# 
#     # RENAME: "SELECT ARCHIVE" -> "INVESTIGATION FILES"
#     app_mode = st.radio("INVESTIGATION FILES", ["CASE FILES", "INTELLIGENCE UNIT"])
# 
#     st.divider()
# 
# # --- 6. MAIN CONTENT ---
# c_icon, c_title = st.columns([1, 15])
# with c_icon: st.image(ICON_URL, width=50)
# with c_title:
#     st.title("FORENSICS xG")
#     st.markdown("##### WHERE THE BEAUTIFUL GAME MEETS HARD EVIDENCE.")
# 
# st.divider()
# 
# if app_mode == "CASE FILES":
#     tabs = st.tabs(["RUBEN AMORIM", "DARREN FLETCHER", "MICHAEL CARRICK", "MAN UTD"])
#     with tabs[0]:
#         st.subheader("SUSPECT: RUBEN AMORIM")
#         st.write("Tactical DNA Analysis")
# 
#         sel_dataset = st.selectbox("CHOOSE EVIDENCE DATASET",
#                                   ["Advanced Goalkeeper Stats Against (2025-2026)", "Passing Efficiency"])
#         df = get_analysis_data(sel_dataset)
# 
#         do_p90 = st.toggle("Convert Data to Per 90")
# 
#         plot_df = df.copy()
#         if do_p90:
#             cols = [c for c in plot_df.columns if c not in ["Player", "90s"]]
#             for col in cols:
#                 plot_df[col] = plot_df[col] / plot_df["90s"]
# 
#         c1, c2, c3 = st.columns(3)
#         metrics = [c for c in plot_df.columns if c != "Player"]
#         x_axis = c1.selectbox("X Metric", metrics, index=0)
#         y_axis = c2.selectbox("Y Metric", metrics, index=1)
#         label_col = c3.selectbox("Label", ["Player"], index=0)
# 
#         fig = px.scatter(plot_df, x=x_axis, y=y_axis, text=label_col, template="plotly_dark")
#         fig.update_traces(marker=dict(size=14, color='#ff4b4b', line=dict(width=1, color='white')), textposition='top center')
#         fig.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(255,255,255,0.05)')
#         st.plotly_chart(fig, use_container_width=True)
# 
# elif app_mode == "INTELLIGENCE UNIT":
#     st.markdown("### 🌍 GLOBAL SCOUTING DATABASE")
#     st.info("Awaiting Clearance...")

!pkill -f localtunnel
!streamlit run forensics_app.py --theme.base="dark" & npx localtunnel --port 8501