# -*- coding: utf-8 -*-
"""Forensics xG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXahst9EouNaxkFii2bNbwgR_lbGrts5
"""

# Install all required libraries
!pip install -q streamlit mplsoccer pandas matplotlib numpy

print("✅ All libraries installed successfully!")

!wget -q -O - ipv4.icanhazip.com

import os
os.makedirs('.streamlit', exist_ok=True)

config_content = """
[theme]
base="dark"
primaryColor="#ff4b4b"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"
[server]
headless = true
enableCORS = false
"""

with open('.streamlit/config.toml', 'w') as f:
    f.write(config_content)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile forensics_app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import requests
# from io import BytesIO
# 
# # --- 1. CONFIGURATION ---
# st.set_page_config(page_title="Forensics xG", layout="wide", page_icon="🧬")
# 
# # --- 2. ASSETS ---
# GITHUB_USER = "jczpineda"
# REPO_NAME = "Forensics-xG"
# FOLDER_PATH = "amorim.csv"
# 
# # --- 3. CSS (THE NUCLEAR VISIBILITY PATCH) ---
# st.markdown("""
#     <style>
#     /* 1. Sidebar Text - Force White */
#     [data-testid="stSidebar"] p, [data-testid="stSidebar"] span, [data-testid="stSidebar"] label {
#         color: white !important;
#         font-size: 14px !important;
#         font-weight: 600 !important;
#     }
# 
#     /* 2. THE DROPDOWN BOX (The part you click) */
#     div[data-baseweb="select"] > div {
#         background-color: #1e293b !important; /* Lighter Slate Blue */
#         color: white !important;
#         border: 1px solid #94a3b8 !important; /* Bright Border */
#     }
# 
#     /* 3. THE DROPDOWN MENU (The list that opens up) */
#     div[data-baseweb="popover"], div[data-baseweb="menu"], ul {
#         background-color: #1e293b !important; /* Force background */
#     }
# 
#     /* 4. TEXT COLOR INSIDE DROPDOWNS */
#     div[data-baseweb="select"] span, div[data-baseweb="menu"] li, li {
#         color: white !important;
#     }
# 
#     /* 5. SVG ICONS (Arrows) */
#     div[data-baseweb="select"] svg {
#         fill: white !important;
#     }
#     </style>
# """, unsafe_allow_html=True)
# 
# # --- 4. INTELLIGENCE ENGINE ---
# if 'cache_cleared' not in st.session_state:
#     st.cache_data.clear()
#     st.session_state.cache_cleared = True
# 
# @st.cache_data(ttl=600)
# def fetch_file_list():
#     api_url = f"https://api.github.com/repos/{GITHUB_USER}/{REPO_NAME}/contents/{FOLDER_PATH}"
#     try:
#         response = requests.get(api_url)
#         if response.status_code == 200:
#             return [f['name'] for f in response.json() if f['name'].endswith(('.csv', '.xlsx'))]
#         return []
#     except:
#         return []
# 
# @st.cache_data
# def load_evidence(filename):
#     raw_url = f"https://raw.githubusercontent.com/jczpineda/{REPO_NAME}/main/{FOLDER_PATH}/{filename}"
#     try:
#         response = requests.get(raw_url)
#         if response.status_code == 200:
#             if filename.endswith('.csv'): return pd.read_csv(BytesIO(response.content))
#             else: return pd.read_excel(BytesIO(response.content))
#     except: return None
#     return None
# 
# # --- 5. SIDEBAR NAVIGATION ---
# with st.sidebar:
#     st.header("🧬 FORENSICS")
#     st.markdown("ANALYSIS UNIT")
#     st.divider()
#     app_mode = st.radio("INVESTIGATION FILES", ["CASE FILES", "INTELLIGENCE UNIT"])
# 
# # --- 6. MAIN CONTENT ---
# st.title("FORENSICS xG")
# st.markdown("**WHERE THE BEAUTIFUL GAME MEETS HARD EVIDENCE.**")
# st.divider()
# 
# if app_mode == "CASE FILES":
#     tabs = st.tabs(["RUBEN AMORIM", "DARREN FLETCHER", "MICHAEL CARRICK", "MAN UTD"])
# 
#     with tabs[0]:
#         st.subheader("SUSPECT: RUBEN AMORIM")
#         st.write("Tactical DNA Analysis")
# 
#         # 1. AUTO-DISCOVERY
#         files = fetch_file_list()
# 
#         if files:
#             # CLEAN NAME MAPPING (Removes .xlsx/.csv)
#             file_map = {f.replace('.xlsx', '').replace('.csv', ''): f for f in files}
# 
#             # DROPDOWN (Uses the Clean Names)
#             sel_clean_name = st.selectbox("CHOOSE EVIDENCE DATASET", list(file_map.keys()))
# 
#             # LOAD REAL FILE
#             real_filename = file_map[sel_clean_name]
#             df = load_evidence(real_filename)
# 
#             if df is not None:
#                 # 2. PER 90 TOGGLE
#                 do_p90 = st.toggle("Convert Data to Per 90")
# 
#                 # Label Logic
#                 label_candidates = ["Player", "Squad", "Team", "Nation", "Opponent"]
#                 label_col = next((c for c in df.columns if c in label_candidates), df.columns[0])
# 
#                 # Data Processing
#                 plot_df = df.copy()
#                 numeric_cols = [c for c in plot_df.columns if pd.api.types.is_numeric_dtype(plot_df[c])]
# 
#                 if do_p90 and "90s" in plot_df.columns:
#                     for c in numeric_cols:
#                         if c != "90s": plot_df[c] = plot_df[c] / plot_df["90s"]
# 
#                 # 3. METRICS SELECTOR
#                 if len(numeric_cols) > 1:
#                     c1, c2 = st.columns(2)
#                     x = c1.selectbox("X Metric", numeric_cols, index=0)
#                     y = c2.selectbox("Y Metric", numeric_cols, index=min(1, len(numeric_cols)-1))
# 
#                     # 4. PLOTLY GRAPH (High Contrast)
#                     fig = px.scatter(plot_df, x=x, y=y, text=label_col, template="plotly_dark")
#                     fig.update_traces(
#                         marker=dict(size=14, color='#ff4b4b', line=dict(width=2, color='white')),
#                         textposition='top center',
#                         textfont=dict(size=12, color='white')
#                     )
#                     fig.update_layout(
#                         height=600,
#                         paper_bgcolor='rgba(0,0,0,0)',
#                         plot_bgcolor='rgba(255,255,255,0.05)',
#                         font=dict(color='white')
#                     )
#                     st.plotly_chart(fig, use_container_width=True)
#                 else:
#                     st.warning("Not enough numeric data columns found.")
#         else:
#             st.error("No evidence files found in archive.")
# 
# elif app_mode == "INTELLIGENCE UNIT":
#     st.info("Module Loading...")

!pkill -f localtunnel
!streamlit run forensics_app.py & npx localtunnel --port 8501