# -*- coding: utf-8 -*-
"""Forensics xG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXahst9EouNaxkFii2bNbwgR_lbGrts5
"""

# Install all required libraries
!pip install -q streamlit mplsoccer pandas matplotlib numpy

print("✅ All libraries installed successfully!")

!wget -q -O - ipv4.icanhazip.com

import os
os.makedirs('.streamlit', exist_ok=True)

# THEME: Dark Base + Explicit Secondary Color for Sidebar
config_content = """
[theme]
base="dark"
primaryColor="#ff4b4b"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#fafafa"
font="sans serif"
[server]
headless = true
enableCORS = false
"""

with open('.streamlit/config.toml', 'w') as f:
    f.write(config_content)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile forensics_app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import requests
# import json
# from io import BytesIO
# 
# # --- 1. CONFIGURATION ---
# st.set_page_config(page_title="Forensics xG", layout="wide", page_icon="🧬")
# 
# # --- 2. ASSETS ---
# GITHUB_USER = "jczpineda"
# REPO_NAME = "Forensics-xG"
# 
# # --- 3. CSS (THE VISIBILITY PATCH) ---
# st.markdown("""
#     <style>
#     /* 1. Force Sidebar Background & Text */
#     [data-testid="stSidebar"] {
#         background-color: #262730 !important; /* Visible Dark Grey */
#         border-right: 1px solid #444 !important;
#     }
#     [data-testid="stSidebar"] * {
#         color: white !important;
#     }
# 
#     /* 2. Force Radio Buttons (JSON Option) to be Visible */
#     div[data-testid="stRadio"] label {
#         color: #f1c40f !important; /* Bright Yellow Text */
#         font-weight: bold !important;
#         font-size: 16px !important;
#     }
# 
#     /* 3. Global Text Safety */
#     h1, h2, h3, p, div, span {
#         color: white !important;
#     }
#     </style>
# """, unsafe_allow_html=True)
# 
# # --- 4. HELPER FUNCTIONS ---
# @st.cache_data(ttl=600)
# def fetch_files_from_path(path=""):
#     api_url = f"https://api.github.com/repos/{GITHUB_USER}/{REPO_NAME}/contents/{path}"
#     try:
#         response = requests.get(api_url)
#         if response.status_code == 200:
#             return response.json()
#         return []
#     except:
#         return []
# 
# @st.cache_data
# def load_file_raw(path):
#     raw_url = f"https://raw.githubusercontent.com/jczpineda/{REPO_NAME}/main/{path}"
#     try:
#         response = requests.get(raw_url)
#         if response.status_code == 200:
#             if path.lower().endswith('.json'): return json.loads(response.content)
#             elif path.lower().endswith('.csv'): return pd.read_csv(BytesIO(response.content))
#             elif path.lower().endswith('.xlsx'): return pd.read_excel(BytesIO(response.content))
#     except: return None
#     return None
# 
# # --- 5. SIDEBAR ---
# with st.sidebar:
#     st.header("🧬 FORENSICS")
#     st.markdown("### ANALYSIS UNIT") # Markdown forces white text via CSS
#     st.divider()
#     app_mode = st.radio("INVESTIGATION FILES", ["CASE FILES", "INTELLIGENCE UNIT"])
# 
# # --- 6. MAIN CONTENT ---
# st.title("🧬 FORENSICS xG")
# st.markdown("**WHERE THE BEAUTIFUL GAME MEETS HARD EVIDENCE.**")
# st.divider()
# 
# if app_mode == "CASE FILES":
#     tabs = st.tabs(["RUBEN AMORIM", "DARREN FLETCHER", "MICHAEL CARRICK", "MAN UTD"])
# 
#     # === RUBEN AMORIM ===
#     with tabs[0]:
#         st.subheader("SUSPECT: RUBEN AMORIM")
# 
#         # RADIO BUTTON (Should be Yellow now)
#         evidence_type = st.radio(
#             "SELECT EVIDENCE TYPE",
#             ["Statistical Reports (CSV/Excel)", "Match Telemetry (JSON)"],
#             horizontal=True
#         )
#         st.divider()
# 
#         # --- OPTION A: STATS ---
#         if evidence_type == "Statistical Reports (CSV/Excel)":
#             items = fetch_files_from_path("amorim.csv")
#             files = [f['name'] for f in items if f['name'].lower().endswith(('.csv', '.xlsx'))]
# 
#             if files:
#                 file_map = {f.replace('.xlsx', '').replace('.csv', ''): f for f in files}
#                 sel_clean = st.selectbox("CHOOSE EVIDENCE DATASET", list(file_map.keys()))
# 
#                 df = load_file_raw(f"amorim.csv/{file_map[sel_clean]}")
#                 if df is not None:
#                     do_p90 = st.toggle("Convert Data to Per 90")
#                     label_candidates = ["Player", "Squad", "Team", "Nation", "Opponent"]
#                     label_col = next((c for c in df.columns if c in label_candidates), df.columns[0])
#                     plot_df = df.copy()
#                     numeric_cols = [c for c in plot_df.columns if pd.api.types.is_numeric_dtype(plot_df[c])]
#                     if do_p90 and "90s" in plot_df.columns:
#                         for c in numeric_cols:
#                             if c != "90s": plot_df[c] = plot_df[c] / plot_df["90s"]
#                     if len(numeric_cols) > 1:
#                         c1, c2 = st.columns(2)
#                         x = c1.selectbox("X Metric", numeric_cols, index=0)
#                         y = c2.selectbox("Y Metric", numeric_cols, index=min(1, len(numeric_cols)-1))
#                         fig = px.scatter(plot_df, x=x, y=y, text=label_col, template="plotly_dark")
#                         fig.update_traces(marker=dict(size=14, color='#ff4b4b', line=dict(width=2, color='white')), textposition='top center')
#                         fig.update_layout(height=600, paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(255,255,255,0.05)', font=dict(color='white'))
#                         st.plotly_chart(fig, use_container_width=True)
#             else:
#                 st.error("No stats files found.")
# 
#         # --- OPTION B: JSON ---
#         elif evidence_type == "Match Telemetry (JSON)":
# 
#             # 1. FIND FOLDER (The "Dragnet")
#             potential_folders = ["amorim.json", "Amorim.json", "Amorim", "amorim"]
#             found_files = []
#             valid_folder = ""
# 
#             # Check specific folders
#             for folder in potential_folders:
#                 items = fetch_files_from_path(folder)
#                 jsons = [f['name'] for f in items if f['name'].lower().endswith('.json')]
#                 if jsons:
#                     found_files = jsons
#                     valid_folder = folder
#                     break
# 
#             # Fallback: Root Scan (Filtered for 'amorim')
#             if not found_files:
#                 root_items = fetch_files_from_path("")
#                 found_files = [
#                     f['name'] for f in root_items
#                     if f['name'].lower().endswith('.json') and 'amorim' in f['name'].lower()
#                 ]
#                 if found_files:
#                     valid_folder = "" # Root
# 
#             if found_files:
#                 # 2. MENU WITH PRETTY NAMES
#                 def make_pretty(filename):
#                     clean = filename.replace(".json", "").replace(".JSON", "").replace("amorim_", "").replace("Amorim_", "")
#                     return f"Man Utd vs {clean}"
# 
#                 sel_json = st.selectbox(
#                     "SELECT MATCH REPORT",
#                     found_files,
#                     format_func=make_pretty
#                 )
# 
#                 # 3. LOAD DATA
#                 full_path = f"{valid_folder}/{sel_json}" if valid_folder else sel_json
#                 match_data = load_file_raw(full_path)
# 
#                 if match_data:
#                     opp_name = sel_json.replace(".JSON", "").replace(".json", "")
#                     st.header(f"⚽ Man Utd vs {opp_name}")
# 
#                     st.markdown("### 🔍 RAW EVENT STRUCTURE")
#                     if isinstance(match_data, list): st.json(match_data[0] if len(match_data) > 0 else {})
#                     elif isinstance(match_data, dict):
#                         st.write(f"Root Keys: {list(match_data.keys())}")
#                         st.json(match_data)
#             else:
#                 st.warning("No JSON files found.")
#                 st.caption("Checked Folders: amorim.json, Amorim, Root")
# 
# elif app_mode == "INTELLIGENCE UNIT":
#     st.info("Awaiting Clearance.")

!pkill -f localtunnel
!streamlit run forensics_app.py & npx localtunnel --port 8501