# -*- coding: utf-8 -*-
"""Forensics xG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXahst9EouNaxkFii2bNbwgR_lbGrts5
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mplsoccer import Pitch, VerticalPitch

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="Forensics xG", layout="wide", page_icon="📂")

# --- CUSTOM CSS FOR FOOTER & STYLING ---
st.markdown("""
    <style>
    /* Dark Theme Backgrounds */
    .stApp {background-color: #0e1117;}

    /* Typography */
    h1, h2, h3 {color: #ff4b4b; font-family: 'Courier New', monospace;}
    .stMetric {background-color: #262730; padding: 10px; border-radius: 5px; border: 1px solid #444;}

    /* CUSTOM FOOTER IMPLEMENTATION */
    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #0e1117;
        color: #808495;
        text-align: center;
        border-top: 1px solid #333;
        padding: 10px;
        z-index: 1000;
        font-family: 'Courier New', monospace;
        font-size: 12px;
    }

    .footer p {
        margin: 0;
        padding: 0;
    }

    .footer-title {
        color: #ff4b4b; /* Red highlight */
        font-weight: bold;
        text-transform: uppercase;
        letter-spacing: 2px;
    }

    /* Adjust main content so it doesn't get hidden behind footer */
    .block-container {
        padding-bottom: 80px;
    }
    </style>

    <div class="footer">
        <p class="footer-title">CASE FILES</p>
        <p>Manchester United 2026-2027 Preparation Dossier</p>
    </div>
    """, unsafe_allow_html=True)

# --- HEADER ---
st.title("📂 FORENSICS xG")
st.markdown("**Subject:** Manchester United 2026-2027 | **Status:** CLASSIFIED")

# --- MOCK DATA GENERATOR ---
def generate_mock_passes(n=50):
    return pd.DataFrame({
        'x': np.random.uniform(0, 120, n),
        'y': np.random.uniform(0, 80, n),
        'outcome': np.random.choice(['Successful', 'Unsuccessful'], n)
    })

# --- TABS ---
tab1, tab2, tab3 = st.tabs(["MATCH REPORT", "MANAGERIAL DNA", "RECRUITMENT"])

with tab1:
    st.header("1. MATCH REPORT")
    col1, col2, col3 = st.columns(3)
    col1.metric("Result", "2 - 1")
    col2.metric("xG", "1.85 - 0.92")
    col3.metric("Field Tilt", "62%")

    st.divider()
    st.subheader("📍 Zone 14 Penetration")
    pitch = Pitch(pitch_type='statsbomb', pitch_color='#0e1117', line_color='#c7d5cc')
    fig, ax = pitch.draw(figsize=(8, 5))
    df_passes = generate_mock_passes(20)
    pitch.scatter(df_passes.x, df_passes.y, ax=ax, c='red', s=80, alpha=0.7)
    st.pyplot(fig)

with tab2:
    st.header("2. MANAGERIAL DNA")
    st.info("Comparison: Amorim vs. Fletcher vs. Carrick")

    # Simple Bar Chart for Manager Style
    style_data = pd.DataFrame({
        'Metric': ['PPDA', 'Direct Speed', 'Field Tilt'],
        'Amorim': [6.5, 1.8, 65],
        'Fletcher': [12.0, 2.2, 40],
        'Carrick': [8.5, 1.4, 55]
    }).set_index('Metric')

    st.bar_chart(style_data)

with tab3:
    st.header("3. RECRUITMENT")
    st.write("Buy/Sell Recommendations based on Tactical Fit")
    st.table(pd.DataFrame({
        'Target': ['Antonio Silva', 'Evan Ferguson'],
        'Club': ['Benfica', 'Brighton'],
        'Fit Score': ['98%', '94%']
    }))